CREATE TABLE IF NOT EXISTS clients(
    Full_Name VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    Nationality VARCHAR(100) NOT NULL,
    ID VARCHAR(13) PRIMARY KEY,
    Passport VARCHAR(50) PRIMARY kEY,
    BankStatement BLOB,
    File_Name VARCHAR(255)
)